language: php
php:
  - 5.4
  - 5.5
  - 5.6
services: mysql
env:
  - DB=mysql
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - mysql -e "CREATE SCHEMA `php-foundation` charset=utf8;"
  - mysql -e "CREATE TABLE `php-foundation`.`pages`(`id` int not null auto_increment, `title` varchar(50), `content` text, `type` varchar(20), primary key (id));"
  - mysql -e "INSERT into `php-foundation`.`pages`(`title`, `content`, `type`) VALUES ('titulo', 'conteudo curto', 'estatico');"
script:
  phpunit --configuration="phpunit.xml" --include-path="."
