language: php
php:
  - 5.4
  - 5.5
  - 5.6
services: mysql
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
script:
  phpunit --configuration="phpunit.xml" --include-path=""
